### ISSUE TITLE
Glitching when dragging

### ISSUE THREAD

**Issue by tombulled** [Icosicon/GameOfLife#2]
When the frame-advance sub-window pops up, once the frame-advance button has been right-clicked, if a user attempts to drag this window, it appears to "jitter" over the screen. ;)

**Comment by wrightom** [comment]
Thanks for flagging this up- I assume you mean the animation window in which case I see what you mean in terms of jittering.
# Part One - *The Problem*
The way the animation currently works is by using a Boolean variable which tells the animator whether or not it should continue to run the next iterations (see `simulatewindow.animate()`, `simulatewindow.simulating`, and `simulatewindow.controllerunactive()`). When the controller (**play** and **pause** button is pressed, several things happen:

1. Like with every release button event function, a sound effect is played using `threading`
2. The value of `simulating` is toggled
3. The graphic of the controller button is toggled (between **play** and **pause**) as a result of `simulating` being toggled
4. If `simulating=True`, ie the animation should be played, `animate` is called- **crucially,** *in the main thread*.

The animator function is as follows:
```
def animate(self):
        self.activecells=self.calcnextframe(self.activecells)  
        if self.simulating:  
            self.master.after(1,self.animate)  
        else:  
            return None
```
As you can see, it is designed to be run in a parallel thread. I would have thought that running it in the main thread would have caused the window to become completely unresponsive but perhaps the window is able to respond in the short space of time between an instance of `animate` calling itself and the next one running, hence the jittering. However, even if this was run in a parallel thread (*I'm not sure if thats the correct terminology but you know what I mean`), I assume that its nested structure would quickly eat up memory. Bearing that in mind...
# Part Two - *The Solution*
`animate` is badly designed- **I admit**. Perhaps a better animation protocol would be:
1. Call a manager function when play is pressed (*in a separate thread*) instead of calling `animate()` directly.
2. While `simulating=True`, do calculate the next iteration and display that.

No nested functions, no thread bottlenecks; happy days, in theory. However, I feel like I've already looked into this and possibly failed, but have no access to that work as it was before I integrated GitHub. Anyway, I'll open a new branch and try implementing what I mentioned above. Any thoughts?

*btw you almost gave me a heart attack when I saw someone other than myself had opened an issue :)*

**Comment by tombulled** [comment]
Hello Tom, thanks for the reply. I was just checking out GitHub after you reccomended it. Tkinter and Threading are two separate things, and they like to stay that way. Running large scrips in the main thread alongside your windows, will cause them to "jitter", I too have experienced this. Even regularly updating the window, will not be a good enough solution. Nested functions are not the problem. Tkinters variables (BooleanVar, StringVar, etc.) do not work in compliance with threading, this was a problem I discovered fairly recently. Seeming as Vexpresso appears to be relatively stable at the moment (fingers crossed), I might take a look into this and see if we can come up with a working compromise. Thanks for the speedy reply, and wish you all the best. - Tom

**Comment by wrightom** [comment]
Tom- **thank you for clearing that up _but..._**
*Please* don't feel at all pressured into releasing your Vexpresso source code! Its yours and yours only - the only reason I put stuff on GitHub is when I have no intention of making *any* money out of it, unless the said money can cover the cost of buying private repositories in which case Git is an amazing workflow tool. I apologise if I made you think you had to share anything in any way; that wasn't my intention.

**Comment by tombulled** [comment]
Haha they should hire you. No you're not pressuring me at all, I do admire you're extremely selfless commitment to you're work though. Im sure one day, you will be making plenty of money, enough even to buy private repositories :))

**Comment by wrightom** [comment]
:)

**Comment by wrightom** [comment]
Just an update- I solved the glitching by animating in a different thread (*see the latest commit to the* `animation-jitter`*branch*). However, this has considerably slowed down the speed of the animation, therefore I'm working on adding window-locking functionality which, when the drag button is left-clicked will toggle the user's ability to move the window, and also whether `animate()` is run in the main thread or its own. Window-lock will own be able to be toggled when `simulating=False`.

**Comment by tombulled** [comment]
Sounds good, you could make it pause the animation completely while the user is dragging the window. If they are dragging it, they are more concerned with where the window is going than what it is doing. By pausing the animation it should become a lot smoother. I am revising at the moment, but once I have done that. I will take a look.

**Comment by tombulled** [comment]
Although my method may not be preferable, it is still one to consider. Hope this helps :)

**Comment by wrightom** [comment]
No definitely much more ingenious than mine- I just had to add `simulating=False` in the drag button function

**Comment by wrightom** [comment]
Aah well, I already made the lock button graphic :)

**Comment by tombulled** [comment]
Well whatever works. I would recommend packaging your code. It's quite a large file. Take a look at this: https://docs.python.org/3/tutorial/modules.html#packages I've just started using it, and it makes code a lot easier to manage.

**Comment by wrightom** [comment]
I'll implement your idea in the master branch seeing as the amount of code I would need to change is so insignificant. Unless you want to do it of course :)

**Comment by wrightom** [comment]
Oops, commented before I read yours. That looks cool, although it looks like it would take a long time for my GoL engine- not even going to try doing it on the Rubik's Cube Simulator :)

**Comment by wrightom** [comment]
I should certainly start using it

**Comment by tombulled** [comment]
Haha no, you go ahead. Nice to be able to help.

**Comment by tombulled** [comment]
Yeah I know what you mean, seeming as they work how they are, you might as well leave them. But I definitely recommend using it when you next start projects. I have the same dilemma with Vexpresso.

**Comment by wrightom** [comment]
Haha, anyway, thanks for your help :). I implemented what we discussed and merged it into the master branch.
